- name: Install splunk shcmember
  hosts: shcmember
  user: splunk

  roles:
    - conf/web
    - conf/outputs
    - conf/server
    - group/searchhead
    - group/shcmember

  post_tasks:
    - name: Run splunk restart
      command: "{{ splunk_installation.splunk_home_path }}/bin/splunk restart"

