---

# - name: Check for Splunk version 6.X
#   find:
#     paths: "{{ splunk_installation.splunk_home_path }}/"
#     patterns: "splunk-6.*manifest"
#   register: splunkv6

# - name: Check for Splunk version 7.X
#   find:
#     paths: "{{ splunk_installation.splunk_home_path }}/"
#     patterns: "splunk-7.*manifest"
#   register: splunkv7

- name: Check if passwd file exists
  stat: path={{ splunk_installation.splunk_home_path }}/etc/passwd
  register: has_passwd_file

- name: Change default password - Splunk 6.x
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk edit user admin -password '{{ splunk_installation.admin_password }}' -auth admin:changeme --accept-license"
  when: 
      - has_passwd_file.stat.exists == false
      - splunkv6.machted is defined

- name: Set admin Password - Splunk 7.X with splunk start
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk start  --accept-license --answer-yes --no-prompt --seed-passwd {{ splunk_installation.admin_password }}"
  when: 
      - has_passwd_file.stat.exists == false
      - splunkv7.matched is  defined
  
- name: Stop splunk after set admin Password
  shell: "{{splunk_installation.splunk_home_path}}/bin/splunk stop"
  when: 
      - has_passwd_file.stat.exists == false
      - splunkv7.matched is  defined
